"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" use vundle to manage bundles
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/bufexplorer.zip'
Plugin 'vim-scripts/AutoClose'
Plugin 'vim-scripts/Tagbar'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'AutoClose'
Plugin 'rking/ag.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'mxw/vim-jsx'
Plugin 'ctrlpvim/ctrlp.vim' " Full path fuzzy file, buffer, mru, tag, ... finder for Vim.
Plugin 'scrooloose/nerdcommenter' " Vim plugin for intensely orgasmic commenting
call vundle#end()

" general settings
set bs=indent,eol,start	" allow backspacing over everything in insert mode
set history=100			" keep 100 lines of command line history
set ruler				" show the cursor position all the time
set ar					" auto read when file is changed from outside
set number		        " show line numbers
set relativenumber

filetype on				" Enable filetype detection
filetype indent on		" Enable filetype-specific indenting
filetype plugin on		" Enable filetype-specific plugins

" auto reload vimrc when editing it
autocmd! bufwritepost .vimrc source ~/.vimrc

syntax on				" syntax highlight
set hlsearch			" search highlighting

set clipboard=unnamed	" yank to the system register (*) by default
set showmatch			" Cursor shows matching ) and }
set showmode			" Show current mode
set wildchar=<TAB>		" start wild expansion in the command line using <TAB>
set wildmenu			" wild char completion menu

" ignore these files while expanding wild chars
set wildignore+=.git 

set autoindent				" auto indentation
set incsearch				" incremental search
set copyindent				" copy the previous indentation on autoindenting
set ignorecase				" ignore case when searching
set smartcase				" ignore case if search pattern is all lowercase,case-sensitive otherwise
set nosmarttab				" insert tabs on the start of a line according to context
set nowrap
set foldmethod=indent
set foldlevel=0

colorscheme desert

" disable sound on errors
set noerrorbells visualbell t_vb=
set tm=500

" tab setting
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set linespace=6
autocmd Filetype ruby set tabstop=2 | set shiftwidth=2 | set softtabstop=2
autocmd Filetype javascript set tabstop=2 | set shiftwidth=2 | set softtabstop=2
autocmd Filetype html set tabstop=2 | set shiftwidth=2 | set softtabstop=2
autocmd Filetype vue set tabstop=2 | set shiftwidth=2 | set softtabstop=2
autocmd Filetype php set tabstop=4 | set shiftwidth=4 | set softtabstop=4

"" always show the status line
set laststatus=2
set titlestring=%{expand('%')}
set statusline=\ CWD:\ %{getcwd()}\ \ Encode:\ %{&fenc}\ \ Line:\ %l/%L

"" useful shortcuts
let mapleader = "f"
let g:mapleader = "f"

"" move to splitted window
map <leader>h :wincmd h<CR> 
map <leader>j :wincmd j<CR> 
map <leader>k :wincmd k<CR> 
map <leader>l :wincmd l<CR> 

" loop to switch windows
nmap <S-w> :wincmd w<CR>

" encoding settings
set encoding=utf-8                                  
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,big5,latin1

" ctags
set tags=tags;/

"" plugin TagBar
let g:tagbar_ctags_bin = '/usr/local/bin/ctags'
let g:tagbar_iconchars = ['+', '-']
let g:tagbar_show_linenumbers = 1
let g:tagbar_width = 50
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 0
let g:tagbar_autoshowtag = 1
nmap <silent> tb :TagbarToggle<cr>
nmap <silent> ta :TagbarOpenAutoClose<cr>


"" plugin BufExplorer
let g:bufExplorerDefaultHelp = 0
let g:bufExplorerSortBy = 'mru'
let g:bufExplorerSplitRight = 1
let g:bufExplorerSplitVertSize = 0
let g:bufExplorerSplitBelow = 1
let g:bufExplorerSplitHorzSize = 0
nmap <silent> be :BufExplorer<cr>
nmap <silent> bh :BufExplorerHorizontalSplit<cr>
nmap <silent> bv :BufExplorerVerticalSplit<cr>


"" plugin NERDTree
let g:NERDTree_title = "NERDTree]"
let g:NERDTreeWinSize = 30
let g:NERDTreeShowLineNumbers = 1
let g:nerdtree_tabs_open_on_gui_startup = 1
let g:nerdtree_tabs_open_on_console_startup = 0
nmap <silent> nt :NERDTreeToggle<cr>


"" plugin ag.vim
"" brew install the_silver_searcher
let g:ag_prg = 'ag --nogroup --nocolor --column'
let g:ag_working_path_mode="r"

"" plugin nerdcommenter
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 0
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java = 1
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
" [count]<leader>cc 单行注释
" [count]<leader>cm 多行注释
" [count]<leader>cl 多行单行注释
" [count]<leader>cu 取消注释

"" plugin ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = {'dir': '\v[\/]\.(git|hg|svn)$', 'file': '\v\.(swp|zip|exe|so|dll)$', 'link': 'some_bad_symbolic_links' }
nmap <leader>p :CtrlP<cr>
