"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" use vundle to manage bundles
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'bufexplorer.zip'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'php.vim'
Plugin 'phpcomplete.vim'
Plugin 'AutoClose'
Plugin 'mileszs/ack.vim'
Plugin 'Tagbar'
Plugin 'neocomplcache'
Plugin 'terryma/vim-multiple-cursors'
call vundle#end()


" general settings
set bs=indent,eol,start	" allow backspacing over everything in insert mode
set history=100			" keep 100 lines of command line history
set ruler				" show the cursor position all the time
set ar					" auto read when file is changed from outside
set nu					" show line numbers

filetype on				" Enable filetype detection
filetype indent on		" Enable filetype-specific indenting
filetype plugin on		" Enable filetype-specific plugins

" auto reload vimrc when editing it
autocmd! bufwritepost .vimrc source ~/.vimrc

syntax on				" syntax highlight
set hlsearch			" search highlighting

set clipboard=unnamed	" yank to the system register (*) by default
set showmatch			" Cursor shows matching ) and }
set showmode			" Show current mode
set wildchar=<TAB>		" start wild expansion in the command line using <TAB>
set wildmenu			" wild char completion menu

" ignore these files while expanding wild chars
set wildignore+=.svn,CVS,.git 
set wildignore+=*.o,*.a,*.class,*.mo,*.la,*.so,*.lo,*.la,*.obj,*.pyc
set wildignore+=*.exe,*.zip,*.jpg,*.png,*.gif,*.jpeg 

set autoindent				" auto indentation
set incsearch				" incremental search
set copyindent				" copy the previous indentation on autoindenting
set ignorecase				" ignore case when searching
set smartcase				" ignore case if search pattern is all lowercase,case-sensitive otherwise
set nosmarttab				" insert tabs on the start of a line according to context
set nowrap

" disable sound on errors
set noerrorbells visualbell t_vb=
set tm=500

" tab setting
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set linespace=5

"" always show the status line
set laststatus=2
set statusline=\ CWD:\ %{getcwd()}%h\ \ Encode:\ %{&fenc}\ \ Line:\ %l/%L

"" useful shortcuts
let mapleader = "f"
let g:mapleader = "f"

"" move to splitted window
map <leader>h :wincmd h<CR> 
map <leader>j :wincmd j<CR> 
map <leader>k :wincmd k<CR> 
map <leader>l :wincmd l<CR> 

" loop to switch windows
nmap <S-w> :wincmd w<CR>

"" encoding settings
set encoding=utf-8                                  
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,big5,latin1


"" plugin TagBar
let g:tagbar_ctags_bin = '/usr/local/bin/ctags'
let g:tagbar_iconchars = ['+', '-']
let g:tagbar_show_linenumbers = 1
let g:tagbar_width = 50
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 0
let g:tagbar_autoshowtag = 1
nmap <silent> tb :TagbarToggle<cr>
nmap <silent> ta :TagbarOpenAutoClose<cr>


"" plugin BufExplorer
let g:bufExplorerDefaultHelp = 0
let g:bufExplorerSortBy = 'mru'
let g:bufExplorerSplitRight = 1
let g:bufExplorerSplitVertSize = 0
let g:bufExplorerSplitBelow = 1
let g:bufExplorerSplitHorzSize = 0
nmap <silent> be :BufExplorer<cr>
nmap <silent> bh :BufExplorerHorizontalSplit<cr>
nmap <silent> bv :BufExplorerVerticalSplit<cr>


"" plugin NERDTree
let g:NERDTree_title = "[NERDTree]"
let g:NERDTreeWinSize = 30
let g:NERDTreeShowLineNumbers = 1
let g:nerdtree_tabs_open_on_gui_startup = 1
let g:nerdtree_tabs_open_on_console_startup = 0
nmap <silent> nt :NERDTreeToggle<cr>

